[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "protobuf_experiments"
version = "0.1.0"
dependencies = [
    "pyyaml",
    "requests",
    "python-telegram-bot[socks]",
]

[tool.setuptools]
packages = { find = { where = ["."] } }

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.coverage.run]
source = ["."]
